module for generator cmd

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -25,3 +25,45 @@ jobs:
             echo "migrations/current.sql has the expected md5sum"
             exit 0
           fi
+      - run: |-
+          docker-compose up
+          
+          # wait for postgres
+          
+          go generate ./...
+      - id: check_generated
+        name: Check Generated Files
+        run: |-
+          DIFF=`git diff -p -- .
+          
+          if [[ ! -z "$DIFF" ]]; then
+            echo "# Generated files don't match" >> $GITHUB_STEP_SUMMARY
+            echo "run yarn generate" >> $GITHUB_STEP_SUMMARY
+            echo '```diff' >> $GITHUB_STEP_SUMMARY
+            echo "$DIFF" | tee -a $GITHUB_STEP_SUMMARY
+            echo "::error Generated files do not match. See job summary for diff."
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "::set-output name=changes::true"
+          fi
+      - name: Create Pull Request
+        id: cpr
+        uses: peter-evans/create-pull-request@v4
+        if: github.event_name == 'pull_request'
+        with:
+          commit-message: Update generated files
+          base: ${{ github.head_ref }}
+          branch: regenerate/${{ github.head_ref }}
+          delete-branch: true
+          title: "Regenerate files for ${{ github.head_ref }}"
+          body: |
+            Update generated files
+          labels: |
+            automated
+          assignees: ${{ !contains(github.actor, '[bot]') && github.actor }}
+          draft: false
+      - name: Fail if there were changes
+        if: ${{ steps.cpr.outputs.pull-request-number }}
+        run: |
+          echo "Generated files don't match, pull request created:"
+          echo "${{ steps.cpr.outputs.pull-request-url }}"
+          exit 1
